# -*- coding: utf-8 -*-
"""Rule_Based_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efNf8yNqN41RbvQDl8JmLCNnbcM5vqiS
"""

# ============================================================
# CORRECT RULE-BASED CARE GAP MODEL
# BASED ON THE ACTUAL 8-TABLE FILE
# ============================================================

# !pip -q install openpyxl

import pandas as pd
import numpy as np
import re

# ============================================================
# 1. SET INPUT FILE PATH
# ============================================================

# INPUT_FILE may be injected by server_api.py at runtime via exec() namespace.
# Only fall back to a default if it was not already provided.
if "INPUT_FILE" not in globals():
    import os as _os
    INPUT_FILE = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "FILTERED_8_TABLES_WITH_NAMES.xlsx")

print("Using file:", INPUT_FILE)

# ============================================================
# 2. READ THE 8 TABLES
# ============================================================

sheets = pd.ExcelFile(INPUT_FILE).sheet_names

required = [
    "PLANS",
    "PLAN_BENEFITS",
    "MEMBERS",
    "MEMBER_ENROLLMENT",
    "MEMBER_HISTORY",
    "CMS_MEASURES",
    "PLAN_MEASURE_PERFORMANCE",
    "PART_D_MEDICATION_HISTORY"
]

for s in required:
    if s not in sheets:
        raise ValueError(f"Missing sheet: {s}")

plans = pd.read_excel(INPUT_FILE, sheet_name="PLANS")
benefits = pd.read_excel(INPUT_FILE, sheet_name="PLAN_BENEFITS")
members = pd.read_excel(INPUT_FILE, sheet_name="MEMBERS")
enrollment = pd.read_excel(INPUT_FILE, sheet_name="MEMBER_ENROLLMENT")
history = pd.read_excel(INPUT_FILE, sheet_name="MEMBER_HISTORY")
cms = pd.read_excel(INPUT_FILE, sheet_name="CMS_MEASURES")
performance = pd.read_excel(
    INPUT_FILE,
    sheet_name="PLAN_MEASURE_PERFORMANCE"
)
meds = pd.read_excel(
    INPUT_FILE,
    sheet_name="PART_D_MEDICATION_HISTORY"
)

# ============================================================
# 3. CLEAN COLUMN NAMES
# ============================================================

def clean_columns(df):
    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

plans = clean_columns(plans)
benefits = clean_columns(benefits)
members = clean_columns(members)
enrollment = clean_columns(enrollment)
history = clean_columns(history)
cms = clean_columns(cms)
performance = clean_columns(performance)
meds = clean_columns(meds)

# ============================================================
# 4. PRINT ACTUAL DATASET INFORMATION
# ============================================================

print("\n================ DATASET =================")

for name, df in {
    "PLANS": plans,
    "PLAN_BENEFITS": benefits,
    "MEMBERS": members,
    "MEMBER_ENROLLMENT": enrollment,
    "MEMBER_HISTORY": history,
    "CMS_MEASURES": cms,
    "PLAN_MEASURE_PERFORMANCE": performance,
    "PART_D_MEDICATION_HISTORY": meds
}.items():

    print(
        f"{name}: {df.shape[0]:,} rows x "
        f"{df.shape[1]} columns"
    )

# ============================================================
# 5. DATE CONVERSION
# ============================================================

def parse_date(series):

    # First try DD-MM-YYYY
    result = pd.to_datetime(
        series,
        format="%d-%m-%Y",
        errors="coerce"
    )

    # Then YYYY-MM-DD
    mask = result.isna()

    if mask.any():

        result.loc[mask] = pd.to_datetime(
            series.loc[mask],
            format="%Y-%m-%d",
            errors="coerce"
        )

    return result


enrollment["enrollment_start_date"] = parse_date(
    enrollment["enrollment_start_date"]
)

enrollment["enrollment_end_date"] = parse_date(
    enrollment["enrollment_end_date"]
)

history["service_date"] = parse_date(
    history["service_date"]
)

history["action_date"] = parse_date(
    history["action_date"]
)

history["completion_date"] = parse_date(
    history["completion_date"]
)

meds["fill_date"] = parse_date(
    meds["fill_date"]
)

# ============================================================
# 6. STANDARDIZE IDS
# ============================================================

members["member_id"] = (
    members["member_id"]
    .astype(str)
    .str.strip()
)

enrollment["member_id"] = (
    enrollment["member_id"]
    .astype(str)
    .str.strip()
)

enrollment["plan_id"] = (
    enrollment["plan_id"]
    .astype(str)
    .str.strip()
)

history["member_id"] = (
    history["member_id"]
    .astype(str)
    .str.strip()
)

meds["member_id"] = (
    meds["member_id"]
    .astype(str)
    .str.strip()
)

cms["measure_id"] = (
    cms["measure_id"]
    .astype(str)
    .str.strip()
)

performance["plan_id"] = (
    performance["plan_id"]
    .astype(str)
    .str.strip()
)

performance["measure_id"] = (
    performance["measure_id"]
    .astype(str)
    .str.strip()
)

benefits["plan_id"] = (
    benefits["plan_id"]
    .astype(str)
    .str.strip()
)

# ============================================================
# 7. REFERENCE DATE
# ============================================================

all_dates = pd.concat(
    [
        history["service_date"],
        meds["fill_date"],
        enrollment["enrollment_end_date"]
    ],
    ignore_index=True
).dropna()

REFERENCE_DATE = all_dates.max()

print(
    "\nReference date:",
    REFERENCE_DATE.strftime("%d-%m-%Y")
)

# ============================================================
# 8. MEMBER → ENROLLMENT → PLAN
# ============================================================

enrollment = enrollment.sort_values(
    ["member_id", "enrollment_start_date"]
)

latest_enrollment = (
    enrollment
    .drop_duplicates(
        "member_id",
        keep="last"
    )
)

base = members.merge(
    latest_enrollment[
        [
            "member_id",
            "plan_id",
            "enrollment_start_date",
            "enrollment_end_date",
            "enrollment_status"
        ]
    ],
    on="member_id",
    how="inner"
)

print(
    "\nMembers after enrollment mapping:",
    len(base)
)

# ============================================================
# 9. KEEP ONLY THE FIVE PLANS
# ============================================================

valid_plans = set(
    plans["plan_id"]
    .astype(str)
)

base = base[
    base["plan_id"].isin(valid_plans)
].copy()

print(
    "Members after plan filtering:",
    len(base)
)

# ============================================================
# 10. ACTUAL CMS MEASURES
# ============================================================

cms["measure_id"] = cms["measure_id"].astype(str)

print("\nCMS MEASURES:")
print(
    cms[
        [
            "measure_id",
            "measure_name",
            "part"
        ]
    ].to_string(index=False)
)

# ============================================================
# 11. PLAN PERFORMANCE
# ============================================================

performance = performance.drop_duplicates(
    ["plan_id", "measure_id"],
    keep="last"
)

performance_lookup = {}

for _, r in performance.iterrows():

    performance_lookup[
        (
            str(r["plan_id"]),
            str(r["measure_id"])
        )
    ] = r

# ============================================================
# 12. HISTORY TEXT CLEANING
# ============================================================

for col in [
    "service_name",
    "test_name",
    "status",
    "intervention_type",
    "outcome",
    "event_type"
]:

    history[col] = (
        history[col]
        .fillna("")
        .astype(str)
        .str.strip()
    )

history["status_lower"] = (
    history["status"]
    .str.lower()
)

history["intervention_lower"] = (
    history["intervention_type"]
    .str.lower()
)

history["outcome_lower"] = (
    history["outcome"]
    .str.lower()
)

# ============================================================
# 13. MEDICATION CLEANING
# ============================================================

meds["claim_status_lower"] = (
    meds["claim_status"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.strip()
)

# Only paid medication claims are valid fills
paid_meds = meds[
    meds["claim_status_lower"] == "paid"
].copy()

# ============================================================
# 14. MEDICATION CLASS
# ============================================================

def medication_class(name):

    x = str(name).lower()

    # Diabetes
    if any(
        word in x
        for word in [
            "metformin",
            "glipizide",
            "insulin",
            "sitagliptin"
        ]
    ):
        return "diabetes"

    # Hypertension / RAS
    if any(
        word in x
        for word in [
            "lisinopril",
            "losartan",
            "enalapril",
            "amlodipine",
            "hydrochlorothiazide"
        ]
    ):
        return "hypertension"

    # Statins
    if any(
        word in x
        for word in [
            "atorvastatin",
            "rosuvastatin",
            "simvastatin",
            "pravastatin",
            "lovastatin",
            "fluvastatin"
        ]
    ):
        return "cholesterol"

    return "other"


paid_meds["med_class"] = (
    paid_meds["medication_name"]
    .apply(medication_class)
)

# ============================================================
# 15. EXACT CONDITION → CMS MEASURE RULES
# ============================================================

condition_rules = {

    "C12": [
        "Diabetes"
    ],

    "C13": [
        "Diabetes"
    ],

    "C14": [
        "Hypertension"
    ],

    "C18": [
        "Heart Failure",
        "Coronary Artery Disease",
        "Stroke"
    ],

    "C19": [
        "Coronary Artery Disease",
        "Peripheral Artery Disease",
        "Stroke"
    ],

    "D08": [
        "Diabetes"
    ],

    "D09": [
        "Hypertension"
    ],

    "D10": [
        "Hyperlipidemia",
        "Coronary Artery Disease",
        "Peripheral Artery Disease",
        "Stroke"
    ],

    "D11": [
        "Diabetes",
        "Hypertension",
        "Hyperlipidemia",
        "Heart Failure"
    ],

    "D12": [
        "Diabetes"
    ]
}

# ============================================================
# 16. PLAN BENEFIT → MEASURE MATCHING
# ============================================================

def plan_supports_measure(
    plan_id,
    measure_id
):

    b = benefits[
        benefits["plan_id"].astype(str)
        == str(plan_id)
    ]

    if b.empty:
        return False

    part = cms.loc[
        cms["measure_id"] == measure_id,
        "part"
    ]

    if len(part) == 0:
        return False

    part = part.iloc[0]

    # --------------------------------------------------------
    # Part C
    # --------------------------------------------------------

    if part == "C":

        service_text = (
            b["service_name"]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        category_text = (
            b["benefit_category"]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        text = (
            service_text
            + " "
            + category_text
        )

        if measure_id == "C12":
            return text.str.contains(
                "hba1c|diabetes",
                regex=True
            ).any()

        if measure_id == "C13":
            return text.str.contains(
                "kidney|renal|urine",
                regex=True
            ).any()

        if measure_id == "C14":
            return text.str.contains(
                "blood pressure|bp check|hypertension",
                regex=True
            ).any()

        if measure_id == "C19":
            return text.str.contains(
                "lipid|cholesterol|statin|vascular|cardiovascular",
                regex=True
            ).any()

        if measure_id == "C18":
            return text.str.contains(
                "hospital|inpatient|readmission",
                regex=True
            ).any()

    # --------------------------------------------------------
    # Part D
    # --------------------------------------------------------

    if part == "D":

        text = (
            b["service_name"]
            .fillna("")
            .astype(str)
            .str.lower()
            + " "
            +
            b["benefit_category"]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        if measure_id == "D08":
            return text.str.contains(
                "diabetes medication|metformin|glipizide",
                regex=True
            ).any()

        if measure_id == "D09":
            return text.str.contains(
                "hypertension|lisinopril|ras",
                regex=True
            ).any()

        if measure_id == "D10":
            return text.str.contains(
                "cholesterol|atorvastatin|statin|cardiovascular",
                regex=True
            ).any()

        if measure_id == "D11":
            return text.str.contains(
                "mtm|medication therapy",
                regex=True
            ).any()

        if measure_id == "D12":
            return text.str.contains(
                "statin|cardiovascular",
                regex=True
            ).any()

    return False

# ============================================================
# 17. HISTORY FOR MEMBER
# ============================================================

history_groups = {
    k: v.copy()
    for k, v in history.groupby("member_id")
}

med_groups = {
    k: v.copy()
    for k, v in paid_meds.groupby("member_id")
}

# ============================================================
# 18. SERVICE MATCHING
# ============================================================

def get_service_history(
    member_id,
    measure_id
):

    h = history_groups.get(
        str(member_id),
        pd.DataFrame()
    )

    if h.empty:
        return h

    if measure_id == "C12":

        return h[
            (
                h["service_name"]
                .str.lower()
                .str.contains(
                    "diabetes",
                    na=False
                )
            )
            |
            (
                h["test_name"]
                .str.lower()
                .str.contains(
                    "hba1c|blood sugar",
                    regex=True,
                    na=False
                )
            )
        ]

    if measure_id == "C13":

        return h[
            (
                h["service_name"]
                .str.lower()
                .str.contains(
                    "kidney",
                    na=False
                )
            )
            |
            (
                h["test_name"]
                .str.lower()
                .str.contains(
                    "kidney|egfr|uacr|albumin|urine",
                    regex=True,
                    na=False
                )
            )
        ]

    if measure_id == "C14":

        return h[
            (
                h["service_name"]
                .str.lower()
                .str.contains(
                    "blood pressure",
                    na=False
                )
            )
            |
            (
                h["test_name"]
                .str.lower()
                .str.contains(
                    "bp check|blood pressure",
                    regex=True,
                    na=False
                )
            )
        ]

    if measure_id == "C19":

        return h[
            (
                h["service_name"]
                .str.lower()
                .str.contains(
                    "cholesterol|heart",
                    regex=True,
                    na=False
                )
            )
            |
            (
                h["test_name"]
                .str.lower()
                .str.contains(
                    "lipid|cholesterol|statin",
                    regex=True,
                    na=False
                )
            )
        ]

    if measure_id == "C18":

        return h[
            (
                h["service_name"]
                .str.lower()
                .str.contains(
                    "hospital|admission|readmission",
                    regex=True,
                    na=False
                )
            )
        ]

    return pd.DataFrame()

# ============================================================
# 19. MEDICATION GAP
# ============================================================

def medication_stats(
    member_id,
    measure_id
):

    m = med_groups.get(
        str(member_id),
        pd.DataFrame()
    )

    if m.empty:

        return {
            "active": 0,
            "missed": 0,
            "adherence": 0,
            "days_since_fill": 0,
            "refill": 0
        }

    required_class = None

    if measure_id in ["D08"]:
        required_class = "diabetes"

    elif measure_id in ["D09"]:
        required_class = "hypertension"

    elif measure_id in ["D10", "D12"]:
        required_class = "cholesterol"

    if required_class is not None:

        m = m[
            m["med_class"] == required_class
        ]

    if m.empty:

        return {
            "active": 0,
            "missed": 0,
            "adherence": 0,
            "days_since_fill": 0,
            "refill": 0
        }

    m = m.sort_values("fill_date")

    latest_fill = m["fill_date"].max()

    days_since_fill = max(
        0,
        (REFERENCE_DATE - latest_fill).days
    )

    refill = pd.to_numeric(
        m["refill_number"],
        errors="coerce"
    ).fillna(0).max()

    missed = 0
    observed = 0
    adherent = 0

    for med_name, g in m.groupby(
        "medication_name"
    ):

        g = g.sort_values(
            "fill_date"
        )

        dates = list(
            g["fill_date"].dropna()
        )

        supplies = list(
            pd.to_numeric(
                g["days_supply"],
                errors="coerce"
            ).fillna(30)
        )

        if len(dates) == 1:

            observed += 1
            adherent += 1

        for i in range(
            len(dates) - 1
        ):

            gap = (
                dates[i + 1]
                -
                dates[i]
            ).days

            expected = supplies[i]

            observed += 1

            if gap <= expected + 7:
                adherent += 1
            else:
                missed += 1

    adherence = (
        adherent / observed
        if observed > 0
        else 0
    )

    return {

        "active":
            int(
                m["medication_name"]
                .nunique()
            ),

        "missed":
            int(missed),

        "adherence":
            round(
                adherence,
                4
            ),

        "days_since_fill":
            int(days_since_fill),

        "refill":
            int(refill)
    }

# ============================================================
# 20. INTERVENTION HISTORY
# ============================================================

def intervention_stats(member_id):

    h = history_groups.get(
        str(member_id),
        pd.DataFrame()
    )

    if h.empty:

        return {
            "count": 0,
            "success": 0,
            "phone": 0,
            "phone_success": 0,
            "sms": 0,
            "sms_success": 0,
            "email": 0,
            "email_success": 0,
            "latest": "No previous intervention"
        }

    h = h[
        h["intervention_lower"].isin(
            [
                "phone call",
                "sms",
                "email"
            ]
        )
    ].copy()

    if h.empty:

        return {
            "count": 0,
            "success": 0,
            "phone": 0,
            "phone_success": 0,
            "sms": 0,
            "sms_success": 0,
            "email": 0,
            "email_success": 0,
            "latest": "No previous intervention"
        }

    def success(row):

        return int(
            row["outcome_lower"]
            == "completed"
        )

    h["success"] = h.apply(
        success,
        axis=1
    )

    phone = h[
        h["intervention_lower"]
        == "phone call"
    ]

    sms = h[
        h["intervention_lower"]
        == "sms"
    ]

    email = h[
        h["intervention_lower"]
        == "email"
    ]

    latest = (
        h.sort_values(
            "service_date",
            ascending=False
        )
        .iloc[0]["intervention_type"]
    )

    return {

        "count":
            len(h),

        "success":
            round(
                h["success"].mean(),
                4
            ),

        "phone":
            len(phone),

        "phone_success":
            round(
                phone["success"].mean()
                if len(phone)
                else 0,
                4
            ),

        "sms":
            len(sms),

        "sms_success":
            round(
                sms["success"].mean()
                if len(sms)
                else 0,
                4
            ),

        "email":
            len(email),

        "email_success":
            round(
                email["success"].mean()
                if len(email)
                else 0,
                4
            ),

        "latest":
            str(latest)
    }

# ============================================================
# 21. SERVICE INFORMATION
# ============================================================

def service_information(
    member_id,
    measure_id
):

    h = get_service_history(
        member_id,
        measure_id
    )

    if h.empty:

        return {
            "service":
                "No recorded service",

            "test":
                "No recorded test",

            "date":
                pd.NaT,

            "missed":
                0,

            "completed":
                0
        }

    h = h.sort_values(
        "service_date",
        ascending=False
    )

    completed = (
        h["status_lower"]
        == "completed"
    )

    missed = (
        h["status_lower"]
        == "missed"
    )

    # Find latest non-empty service
    service = "No recorded service"

    for x in h["service_name"]:

        if str(x).strip():
            service = str(x).strip()
            break

    # Find latest non-empty test
    test = "No recorded test"

    for x in h["test_name"]:

        if str(x).strip():
            test = str(x).strip()
            break

    date = (
        h["service_date"]
        .dropna()
        .max()
        if h["service_date"].notna().any()
        else pd.NaT
    )

    return {

        "service": service,

        "test": test,

        "date": date,

        "missed": int(
            missed.sum()
        ),

        "completed": int(
            completed.sum()
        )
    }

# ============================================================
# 22. DETERMINE CARE GAP
# ============================================================

def is_care_gap(
    row,
    measure_id
):

    # --------------------------------------------------------
    # C12 - Blood Sugar Controlled
    # --------------------------------------------------------

    if measure_id == "C12":

        h = get_service_history(
            row["member_id"],
            "C12"
        )

        if h.empty:
            return True

        completed = h[
            h["status_lower"]
            == "completed"
        ]

        if completed.empty:
            return True

        # If result is uncontrolled, gap
        result = (
            completed["result"]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        if result.str.contains(
            "uncontrolled|not controlled|poor",
            regex=True
        ).any():

            return True

        return False

    # --------------------------------------------------------
    # C13 - Kidney Health Evaluation
    # --------------------------------------------------------

    if measure_id == "C13":

        h = get_service_history(
            row["member_id"],
            "C13"
        )

        if h.empty:
            return True

        completed_tests = h[
            h["status_lower"]
            == "completed"
        ]

        if completed_tests.empty:
            return True

        text = (
            completed_tests["test_name"]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        # Need evidence of both kidney evaluation
        # components
        has_kidney = text.str.contains(
            "kidney|egfr",
            regex=True
        ).any()

        has_urine = text.str.contains(
            "urine|uacr|albumin",
            regex=True
        ).any()

        return not (
            has_kidney and has_urine
        )

    # --------------------------------------------------------
    # C14 - Blood Pressure
    # --------------------------------------------------------

    if measure_id == "C14":

        h = get_service_history(
            row["member_id"],
            "C14"
        )

        if h.empty:
            return True

        completed = h[
            h["status_lower"]
            == "completed"
        ]

        if completed.empty:
            return True

        return False

    # --------------------------------------------------------
    # C19 - Statin Therapy for CVD
    # --------------------------------------------------------

    if measure_id == "C19":

        m = med_groups.get(
            str(row["member_id"]),
            pd.DataFrame()
        )

        if m.empty:
            return True

        statins = m[
            m["med_class"]
            == "cholesterol"
        ]

        return statins.empty

    # --------------------------------------------------------
    # C18 - Readmission
    # --------------------------------------------------------

    if measure_id == "C18":

        # There is no reliable hospitalization/readmission
        # event in the supplied MEMBER_HISTORY.
        #
        # Therefore do NOT fabricate a care gap.
        return False

    # --------------------------------------------------------
    # D08 - Diabetes Medication
    # --------------------------------------------------------

    if measure_id == "D08":

        s = medication_stats(
            row["member_id"],
            "D08"
        )

        return (
            s["active"] == 0
            or
            s["adherence"] < 0.80
            or
            s["days_since_fill"] > 60
        )

    # --------------------------------------------------------
    # D09 - Hypertension Medication
    # --------------------------------------------------------

    if measure_id == "D09":

        s = medication_stats(
            row["member_id"],
            "D09"
        )

        return (
            s["active"] == 0
            or
            s["adherence"] < 0.80
            or
            s["days_since_fill"] > 60
        )

    # --------------------------------------------------------
    # D10 - Cholesterol Medication
    # --------------------------------------------------------

    if measure_id == "D10":

        s = medication_stats(
            row["member_id"],
            "D10"
        )

        return (
            s["active"] == 0
            or
            s["adherence"] < 0.80
            or
            s["days_since_fill"] > 60
        )

    # --------------------------------------------------------
    # D11 - MTM
    # --------------------------------------------------------

    if measure_id == "D11":

        h = history_groups.get(
            str(row["member_id"]),
            pd.DataFrame()
        )

        if h.empty:
            return False

        text = (
            h.fillna("")
            .astype(str)
            .agg(
                " ".join,
                axis=1
            )
            .str.lower()
        )

        mtm = text.str.contains(
            "mtm|medication therapy management|cmr|comprehensive medication review",
            regex=True
        )

        # Only evaluate members for whom MTM evidence exists
        if not mtm.any():
            return False

        completed = text.str.contains(
            "cmr|comprehensive medication review",
            regex=True
        )

        return not completed.any()

    # --------------------------------------------------------
    # D12 - Statin Use in Diabetes
    # --------------------------------------------------------

    if measure_id == "D12":

        m = med_groups.get(
            str(row["member_id"]),
            pd.DataFrame()
        )

        if m.empty:
            return True

        statins = m[
            m["med_class"]
            == "cholesterol"
        ]

        return statins.empty

    return False

# ============================================================
# 23. OUTPUT COLUMNS
# ============================================================

OUTPUT_COLUMNS = [

    "patient_id",
    "plan_id",
    "care_gap",
    "age",
    "gender",
    "condition",
    "condition_code",
    "part",
    "measure_id",
    "measure_type",
    "measure_weight",
    "service_name",
    "test_name",
    "performance_value",
    "measure_star",
    "enrollment_status",
    "enrollment_tenure_days",
    "missed_service_count",
    "completed_service_count",
    "days_since_last_service",
    "previous_intervention_count",
    "previous_success_rate",
    "previous_phone_count",
    "phone_success_rate",
    "previous_sms_count",
    "sms_success_rate",
    "previous_email_count",
    "email_success_rate",
    "active_medication_count",
    "missed_refill_count",
    "medication_adherence_rate",
    "days_since_last_fill",
    "refill_number",
    "intervention_type"
]

# ============================================================
# 24. BUILD RULE ENGINE
# ============================================================

results = []

diagnostics = []

for _, row in base.iterrows():

    member_id = str(
        row["member_id"]
    )

    plan_id = str(
        row["plan_id"]
    )

    condition = str(
        row["condition"]
    ).strip()

    for _, measure in cms.iterrows():

        measure_id = str(
            measure["measure_id"]
        )

        measure_name = str(
            measure["measure_name"]
        )

        part = str(
            measure["part"]
        )

        # ----------------------------------------------------
        # CONDITION ELIGIBILITY
        # ----------------------------------------------------

        allowed_conditions = (
            condition_rules
            .get(
                measure_id,
                []
            )
        )

        eligible = any(
            condition.lower()
            == allowed.lower()
            for allowed
            in allowed_conditions
        )

        if not eligible:

            continue

        # ----------------------------------------------------
        # PLAN BENEFIT SUPPORT
        # ----------------------------------------------------

        supported = plan_supports_measure(
            plan_id,
            measure_id
        )

        # Do not force unsupported benefit
        if not supported:

            continue

        # ----------------------------------------------------
        # C18 HAS NO PATIENT-LEVEL DATA
        # ----------------------------------------------------

        if measure_id == "C18":

            continue

        # ----------------------------------------------------
        # CHECK CARE GAP
        # ----------------------------------------------------

        gap = is_care_gap(
            row,
            measure_id
        )

        if not gap:

            continue

        # ----------------------------------------------------
        # SERVICE INFORMATION
        # ----------------------------------------------------

        info = service_information(
            member_id,
            measure_id
        )

        # For medication measures, use meaningful
        # service/test names even when no previous
        # service exists.

        medication_service_names = {

            "D08": (
                "Diabetes Medication Adherence",
                "Medication Refill"
            ),

            "D09": (
                "Hypertension Medication Adherence",
                "Medication Refill"
            ),

            "D10": (
                "Cholesterol Medication Adherence",
                "Statin Refill"
            ),

            "D11": (
                "Medication Therapy Management",
                "Comprehensive Medication Review"
            ),

            "D12": (
                "Statin Therapy",
                "Statin Prescription Fill"
            )
        }

        if measure_id in medication_service_names:

            service_name, test_name = (
                medication_service_names[
                    measure_id
                ]
            )

        else:

            service_name = info["service"]

            test_name = info["test"]

        # ----------------------------------------------------
        # DAYS SINCE SERVICE
        # ----------------------------------------------------

        if pd.notna(info["date"]):

            days_since_service = max(
                0,
                (
                    REFERENCE_DATE
                    -
                    info["date"]
                ).days
            )

        else:

            days_since_service = 0

        # ----------------------------------------------------
        # INTERVENTION
        # ----------------------------------------------------

        istats = intervention_stats(
            member_id
        )

        intervention_type = (
            istats["latest"]
        )

        # ----------------------------------------------------
        # MEDICATION
        # ----------------------------------------------------

        medstats = medication_stats(
            member_id,
            measure_id
        )

        # ----------------------------------------------------
        # PERFORMANCE
        # ----------------------------------------------------

        perf = performance_lookup.get(
            (
                plan_id,
                measure_id
            )
        )

        if perf is not None:

            performance_value = pd.to_numeric(
                perf.get(
                    "performance_value",
                    0
                ),
                errors="coerce"
            )

            measure_star = pd.to_numeric(
                perf.get(
                    "measure_star",
                    0
                ),
                errors="coerce"
            )

            # IMPORTANT:
            # Performance table has weight.
            # Output must be measure_weight.

            measure_weight = pd.to_numeric(
                perf.get(
                    "weight",
                    measure.get(
                        "weight",
                        1
                    )
                ),
                errors="coerce"
            )

        else:

            performance_value = 0
            measure_star = 0

            measure_weight = pd.to_numeric(
                measure.get(
                    "weight",
                    1
                ),
                errors="coerce"
            )

        if pd.isna(performance_value):
            performance_value = 0

        if pd.isna(measure_star):
            measure_star = 0

        if pd.isna(measure_weight):
            measure_weight = 1

        # ----------------------------------------------------
        # ENROLLMENT TENURE
        # ----------------------------------------------------

        start_date = row[
            "enrollment_start_date"
        ]

        if pd.notna(start_date):

            tenure = max(
                0,
                (
                    REFERENCE_DATE
                    -
                    start_date
                ).days
            )

        else:

            tenure = 0

        # ----------------------------------------------------
        # BUILD 34-ATTRIBUTE RECORD
        # ----------------------------------------------------

        results.append({

            "patient_id":
                member_id,

            "plan_id":
                plan_id,

            "care_gap":
                measure_name,

            "age":
                row["age"],

            "gender":
                row["gender"],

            "condition":
                row["condition"],

            "condition_code":
                row["condition_code"],

            "part":
                part,

            "measure_id":
                measure_id,

            "measure_type":
                measure["measure_type"],

            "measure_weight":
                float(
                    measure_weight
                ),

            "service_name":
                service_name,

            "test_name":
                test_name,

            "performance_value":
                float(
                    performance_value
                ),

            "measure_star":
                float(
                    measure_star
                ),

            "enrollment_status":
                row["enrollment_status"],

            "enrollment_tenure_days":
                int(tenure),

            "missed_service_count":
                int(info["missed"]),

            "completed_service_count":
                int(info["completed"]),

            "days_since_last_service":
                int(
                    days_since_service
                ),

            "previous_intervention_count":
                int(
                    istats["count"]
                ),

            "previous_success_rate":
                float(
                    istats["success"]
                ),

            "previous_phone_count":
                int(
                    istats["phone"]
                ),

            "phone_success_rate":
                float(
                    istats["phone_success"]
                ),

            "previous_sms_count":
                int(
                    istats["sms"]
                ),

            "sms_success_rate":
                float(
                    istats["sms_success"]
                ),

            "previous_email_count":
                int(
                    istats["email"]
                ),

            "email_success_rate":
                float(
                    istats["email_success"]
                ),

            "active_medication_count":
                int(
                    medstats["active"]
                ),

            "missed_refill_count":
                int(
                    medstats["missed"]
                ),

            "medication_adherence_rate":
                float(
                    medstats["adherence"]
                ),

            "days_since_last_fill":
                int(
                    medstats["days_since_fill"]
                ),

            "refill_number":
                int(
                    medstats["refill"]
                ),

            "intervention_type":
                intervention_type
        })

# ============================================================
# 25. CREATE FINAL DATAFRAME
# ============================================================

output = pd.DataFrame(
    results
)

# Force exact 34 columns
output = output[
    OUTPUT_COLUMNS
].copy()

# ============================================================
# 26. REMOVE DUPLICATE PATIENT + MEASURE
# ============================================================

output = output.drop_duplicates(
    subset=[
        "patient_id",
        "plan_id",
        "measure_id"
    ]
).reset_index(
    drop=True
)

# ============================================================
# 27. NO NULL VALUES
# ============================================================

text_columns = [
    "patient_id",
    "plan_id",
    "care_gap",
    "gender",
    "condition",
    "condition_code",
    "part",
    "measure_id",
    "measure_type",
    "service_name",
    "test_name",
    "enrollment_status",
    "intervention_type"
]

for c in text_columns:

    output[c] = (
        output[c]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
    )

numeric_columns = [
    "age",
    "measure_weight",
    "performance_value",
    "measure_star",
    "enrollment_tenure_days",
    "missed_service_count",
    "completed_service_count",
    "days_since_last_service",
    "previous_intervention_count",
    "previous_success_rate",
    "previous_phone_count",
    "phone_success_rate",
    "previous_sms_count",
    "sms_success_rate",
    "previous_email_count",
    "email_success_rate",
    "active_medication_count",
    "missed_refill_count",
    "medication_adherence_rate",
    "days_since_last_fill",
    "refill_number"
]

for c in numeric_columns:

    output[c] = pd.to_numeric(
        output[c],
        errors="coerce"
    ).fillna(0)

# ============================================================
# 28. FINAL VALIDATION
# ============================================================

print("\n")
print("=" * 70)
print("FINAL RULE ENGINE RESULT")
print("=" * 70)

print(
    "Total records:",
    len(output)
)

print(
    "Total attributes:",
    len(output.columns)
)

print(
    "\nExpected attributes: 34"
)

print(
    "\nNull values:"
)

nulls = output.isna().sum()

print(
    nulls[nulls > 0]
)

print(
    "\nCare gap distribution:"
)

if len(output) > 0:

    print(
        output[
            "care_gap"
        ].value_counts()
    )

else:

    print(
        "WARNING: ZERO RECORDS"
    )

print(
    "\nPlan distribution:"
)

if len(output) > 0:

    print(
        output[
            "plan_id"
        ].value_counts()
    )

# ============================================================
# 29. CARE GAP COUNT
# ============================================================

if len(output) > 0:

    care_gap_count = (
        output
        .groupby(
            [
                "plan_id",
                "part",
                "measure_id",
                "care_gap"
            ]
        )
        .size()
        .reset_index(
            name="care_gap_count"
        )
    )

    plan_count = (
        output
        .groupby(
            "plan_id"
        )
        .size()
        .reset_index(
            name="total_care_gap_count"
        )
    )

else:

    care_gap_count = pd.DataFrame(
        columns=[
            "plan_id",
            "part",
            "measure_id",
            "care_gap",
            "care_gap_count"
        ]
    )

    plan_count = pd.DataFrame(
        columns=[
            "plan_id",
            "total_care_gap_count"
        ]
    )

# ============================================================
# 30. SAVE EXCEL
# ============================================================

OUTPUT_FILE = (
    "CORRECTED_RULE_ENGINE_34_ATTRIBUTES.xlsx"
)

with pd.ExcelWriter(
    OUTPUT_FILE,
    engine="openpyxl"
) as writer:

    output.to_excel(
        writer,
        sheet_name="RULE_ENGINE_OUTPUT",
        index=False
    )

    care_gap_count.to_excel(
        writer,
        sheet_name="CARE_GAP_COUNT",
        index=False
    )

    plan_count.to_excel(
        writer,
        sheet_name="PLAN_CARE_GAP_COUNT",
        index=False
    )

print(
    "\nSaved:",
    OUTPUT_FILE
)